name: 'Remove installed certificates'
description: 'This action removes installed certificates.'
inputs:
  type:
    description: >
      Specify the type of certificate to search for.

      Possible options are:
      Development, Distribution
    required: false
  publisher:
    description: >
      Specify the name of the issuer if the issuer is the target of the search.
    required: false
  issuer-id:
    description: >
      Specify the issuer identifier when the search is for the issuer identifier.
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: "box"
  color: "orange"