name: Test

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  Test:
    runs-on: macos-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          type: Development
          publisher: Akio Jinsenji
